title: RIGNITC Placement-testimonials
description: A website for guiding RIGNITC Members in Interview Preparation and Placement
theme: just-the-docs

url: https://rignitc.github.io/placement-testimonials

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
